### PR TITLE
change the namespace salt the same as PHP&Js. implementation.

### PR DESCRIPTION
**Pull request by yjqg6666**
Incompatible with previously running test due to salt change.

### CODE REVIEW

**Review by nkconnor — COMMENTED** [review]
Thanks for the contribution!

How does this differ from `getHash` with no fullSalt in `ops.random.PlanOutOpRandom`?

Also, on the `.travis.yml` commit.. I will work on getting a build agent set-up.

**Comment by yjqg6666** [comment]
As https://github.com/nkconnor/planout4j/blob/master/core/src/main/java/com/glassdoor/planout4j/planout/ops/random/PlanOutOpRandom.java#L62-L67  AND https://github.com/nkconnor/planout4j/blob/master/core/src/main/java/com/glassdoor/planout4j/planout/ops/random/PlanOutOpRandom.java#L116, If do not specify the full salt, the full salt would  be null.x when 
NamespaceConfig.addExperiment -> NamespaceConfig.allocateSegments  -> Sample.eval 
AND
NamespaceConfig.getExperiment -> NamespaceConfig.getSegment -> RandomInteger.eval .

In PHP impl., https://github.com/vimeo/ABLincoln/blob/56c33c0ee5159720a6dcd4625139693ad0497997/src/Vimeo/ABLincoln/Namespaces/SimpleNamespace.php#L124-L125, the salt is [namespace.name]. sampled_segments when addExperiment,  https://github.com/vimeo/ABLincoln/blob/56c33c0ee5159720a6dcd4625139693ad0497997/src/Vimeo/ABLincoln/Namespaces/SimpleNamespace.php#L171-L172 the salt is [namespace.name]. segment when getSegment.

In Node.Js impl., https://github.com/HubSpot/PlanOut.js/blob/acb658e2b5b321e3ec2fc0e73ef26cb3c9d12ce0/es6/namespace.js#L116-L117 AND https://github.com/HubSpot/PlanOut.js/blob/acb658e2b5b321e3ec2fc0e73ef26cb3c9d12ce0/es6/namespace.js#L148-L149,  It's almost the same as the PHP impl..

**Comment by yjqg6666** [comment]
Now only when "crossLanguageMode = true" exists in the backend section of planout4j.conf, the new salting would be used.

**Review by nkconnor — APPROVED** [review]
Ok, this looks great.

**Pull request merged**
